version: '3.2'


services:

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - net
      - common
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - db:/var/lib/postgresql/data/
    depends_on:
      - nextcloud_db
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - NEXTCLOUD_HOSTNAME
      - NEXTCLOUD_TRUSTED_DOMAINS

    hostname: ${VIRTUAL_HOST}

  nextcloud_db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks: 
      - common

  redis:
    image: redis
    container_name: nextcloud_redis
    networks:
      - common
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  cron:
    image: nextcloud
    container_name: nextcloud_cron
    restart: always
    networks:
      - net
      - common
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - redis
      
  coturn:
    image: woahbase/alpine-coturn
    container_name: coturn
    volumes:
      - "./coturn/turnserver.conf:/var/lib/coturn/turnserver.conf"
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478"
    restart: always

volumes:
  nextcloud:
  db:

networks:
  net:
    external: true
  common:
    internal: true
  